### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [mapillary/metropolis_sdk#1]
Need help.

Thanks!

**Comment by ducksoup** [comment]
Can you please elaborate on your issue? Are you having problems with the dataset's [download page](https://www.mapillary.com/dataset/metropolis)?

**Comment by Yannnnnnnnnnnn** [comment]
I could not download the dataset from https://www.mapillary.com/dataset/metropolis yesterday, but it works now! 
I am sorry that I did not record what happened at that time.

Thanks for your reply, and I will close this issue as the link is fixed.

**Comment by Yannnnnnnnnnnn** [comment]
I tried to download mapillary_metropolis_v1_images.zip and I think my network is okay.
![image](https://user-images.githubusercontent.com/17909171/147188470-a8e7ca5b-3b62-402c-9890-d1ca54ad6961.png)
![image](https://user-images.githubusercontent.com/17909171/147188518-ca440984-19a2-4372-880b-0aef80048ae6.png)

**Comment by mherb** [comment]
I have the same/similar issue downloading the dataset. While some downloads (e.g. annotations, panoptic) do work for me, the images.zip and pointcloud.zip do not work with similar issues as @Yannnnnnnnnnnn is experiencing. For images.zip I consistently get "400 Bad Request" as http response. And pointcloud.zip will not start to download at all (0bytes/s) or will download the first ~10MB just fine and then drop to 0bytes/s.

I tested this with different internet connections on different days and (judging from the download URLs) resulting in different CDN mirrors (Munich and Hamburg in my case) all with the same behaviour.

Any updates on this @ducksoup ?

**Comment by mherb** [comment]
Update: Issue seems to have resolved itself (at least for me), was able to download all files yesterday at full speed, maybe you want to try again @Yannnnnnnnnnnn in case you haven't already

**Comment by Yannnnnnnnnnnn** [comment]
@mherb Thanks for your remind. I tried again, but I got a "400 Bad Request" this time.

**Comment by ducksoup** [comment]
@mherb @Yannnnnnnnnnnn Sorry for the late response. We are currently looking into this issue and will come back to you as soon as we have an update.

**Comment by ducksoup** [comment]
@Yannnnnnnnnnnn quick update: we have identified an issue in our CDN related to handling extremely large files. I'll notify you when the issue is solved.

**Comment by Yannnnnnnnnnnn** [comment]
Thank you for your reply!

I think the problem is that the download link is not very stable. I successfully downloaded the dataset on one of my computers but got a 400 on another.
