### ISSUE TITLE
Where to get CAD models

### ISSUE THREAD

**Issue by shubham1810** [mapillary/metropolis_sdk#2]
I am trying to look for the CAD models as per the information on the dataset website but can't find them. Please let me know if it is available yet?

Essentially I want to visualize the scene in the second column from the below image (taken from dataset website) 

![Screenshot from 2022-01-19 13-35-21](https://user-images.githubusercontent.com/5525923/150089518-a37e85be-28af-4a0c-a9ec-d854f5b7fe10.png)

Thanks!

**Comment by ducksoup** [comment]
@shubham1810 the CAD models are distributed as a single PLY file (`cad.mesh.ply`) included in the same archive where the point clouds are, i.e. `mapillary_metropolis_v1_point_clouds.zip`. These meshes can be interpreted in the same coordinates system as the other point cloud files, for guidance please refer to the [metropolis_crop_point_clouds](scripts/metropolis_crop_point_clouds) script.

Note that for now the SDK doesn't include a visualization function for the CAD models, but we are planning to release it as soon as possible.

**Comment by shubham1810** [comment]
@ducksoup Thank you for the prompt response! I believe I will be able to test the scripts once #1 is resolved as well.

**Comment by jeannotes** [comment]
@ducksoup 
when I look up the reference image above(from left to right:pointcloud, cad render depth, original img), I do find something:
![9](https://user-images.githubusercontent.com/13599324/183600253-4c1bcb19-a1c9-44c1-ba6a-606b7bfffa68.png)

I make some visualization arrows for better understanding.
seems the accuray of reconstruction not that high?
